- name: Download and Add Powershell Key to Apt-Get Keyring
  apt_key:
    url: "https://packages.microsoft.com/keys/microsoft.asc"
    state: present

- name: Add Powershell Repository into /etc/apt/sources.list - Bionic
  apt_repository:
    repo: 'deb [arch=amd64] https://packages.microsoft.com/ubuntu/18.04/prod bionic main'
    state: present

- name: Install Powershell
  apt:
    pkg: powershell
    state: latest
    force: yes
